# Generated by Django 5.0.3 on 2024-03-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='ne', max_length=100)),
                ('lastname', models.CharField(default='ne', max_length=100)),
                ('password', models.CharField(default='ne', max_length=100)),
            ],
        ),
    ]
